version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
    volumes:
      - ./db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    #command: php /app2/artisan serve --host=0.0.0.0 --port=8080 
    volumes:
      - ./app/:/var/www/html
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    ports:
      - 7000:80

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7070:80 
